### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by rtanglao** [walkah/walkah.net#11]
how do you decide what to do each day?

**Comment by walkah** [comment]
thanks, @rtanglao ! this is a good one (and really an ongoing process).

**Comment by rtanglao** [comment]
james just blog your to do list strategy once a year ! so we can see the evolution of your awesome thinking :-)

**Comment by rtanglao** [comment]
nice thanks for doing this soooo quickly!

**Comment by walkah** [comment]
Anytime! Thanks for the idea :+1:
